apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bloggin-cert
spec:
  secretName: bloggin-tls
  commonName: kloudninja.online
  privateKeySecretRef:
    rotationPolicy: Always
    algorithm: ECDSA
    encoding: PKCS8
    size: 256

  usages:
  - client auth
  - server auth

     
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - "*.kloudninja.online"

  