
# deployment using canary deployment

name: Simple App Deployment
on: 
    push: 
      branches: 
        - main

jobs: 
  bloggin-deployment:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps: 
      - name: "first run job"
        run: |
          echo "--- welcome to bloggin app ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "VERSION_NUMBER=${RANDOM}" >> $GITHUB_ENV
      
      - name: "Build a Docker image from the repo v1"
        run:  | 
          docker build -t healerkay/bloggin:${{ env.VERSION_NUMBER}} .

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push healerkay/bloggin:${{ env.VERSION_NUMBER }}

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}

      - name: "Connect to the cluster"
        run: |
          aws eks update-kubeconfig --name cluster


      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"

      - name: "Use helm to install our charts"
        run: |
          helm upgrade --install bloggin bloggin -f bloggin/values.yaml --set image.tag=${{ env.VERSION_NUMBER}} --set replicaCount=3 --set canaryImage.tag=${{ env.APP_VERSION}} --set canaryReplica=1
      
      - name: "Announce the latest version of the deployment"
        uses: dawidd6/action-send-mail@v3
        with:
                username: taykeny94@gmail.com
                password: ${{ secrets.EMAIL_PASSWORD }}
                server_address: smtp.gmail.com
                server_port: 465
                secure: true
                subject: "New Docker Image Version for bloggin Web App - canary Deployment"
                to: "abatankehinde1999@gmail.com, taiwoabatan66@gmail.com"
                from: Abatan kehinde <taykeny94@gmail.com>
                body: "New image build: healerkay/bloggin:${{ env.VERSION_NUMBER }}"

 
  canary-deployment:
    if: ${{ github.ref_name == 'canary' }}
    runs-on: ubuntu-latest
    steps: 
      - name: "first run job"
        run: |
          echo "--- welcome to bloggin app ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "VERSION_NUMBER=${RANDOM}" >> $GITHUB_ENV
      
      - name: "Build a Docker image from the repo v1"
        run:  | 
          docker build -t healerkay/bloggin:${{ env.VERSION_NUMBER}} .

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push healerkay/bloggin:${{ env.VERSION_NUMBER }}

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}

      - name: "Connect to the cluster"
        run: |
          aws eks update-kubeconfig --name cluster


      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"

      - name: "Use helm to install our charts"
        run: |
          helm upgrade --install bloggin bloggin -f bloggin/values.yaml --set canary.tag=${{ env.VERSION_NUMBER}} --set replicaCount=2 --set canaryReplica=2


      - name: "Announce the latest version of the deployment"
        uses: dawidd6/action-send-mail@v3
        with:
                username: taykeny94@gmail.com
                password: ${{ secrets.EMAIL_PASSWORD }}
                server_address: smtp.gmail.com
                server_port: 465
                secure: true
                subject: "New Docker Image Version for bloggin Web App - canary Deployment"
                to: "abatankehinde1999@gmail.com, taiwoabatan66@gmail.com"
                from: Abatan kehinde <taykeny94@gmail.com>
                body: "New image build: healerkay/bloggin:${{ env.VERSION_NUMBER }}"